services:
    estructura:
        image: sysacad:v1.0.0
        networks:
          - leared
        ports:
          - 5000:5000
        environment:
          - FLASK_CONTEXT=${FLASK_CONTEXT}
          - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}  
          - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
          - PROD_DATABASE_URI=${PROD_DATABASE_URI}
          - DEV_DATABASE_URI=${DEV_DATABASE_URI}
          - TEST_DATABASE_URI=${TEST_DATABASE_URI}
          - HASHIDS_ALPHABET=${HASHIDS_ALPHABET}
          - HASHIDS_SALT=${HASHIDS_SALT}
          - SECRET_KEY=${SECRET_KEY}
          - HASHIDS_MIN_LENGTH=${HASHIDS_MIN_LENGTH}
networks:
    leared:
        external: true
