from .alumno import Alumno
from .area import Area
from .autoridad import Autoridad
from .cargo import Cargo
from .categoriacargo import CategoriaCargo
from .departamento import Departamento
from .especialidad import Especialidad
from .facultad import Facultad
from .grado import Grado
from .grupo import Grupo
from .materia import Materia
from .orientacion import Orientacion
from .plan import Plan
from .tipodedicacion import TipoDedicacion
from .tipodocumento import TipoDocumento
from .tipoespecialidad import TipoEspecialidad
from .universidad import Universidad
