from .tipodocumento import TipoDocumento
from .alumno import Alumno
from .area import Area
from .categoriacargo import CategoriaCargo
from .departamento import Departamento
from .facultad import Facultad
from .grado import Grado
from .grupo import Grupo
from .tipodedicacion import TipoDedicacion
from .tipoespecialidad import TipoEspecialidad
from .universidad import Universidad
from .cargo import Cargo
from .autoridad import Autoridad
from .especialidad import Especialidad
from .plan import Plan
from .materia import Materia
from .orientacion import Orientacion