from .facultad_repositorio import FacultadRepository
from .grado_repositorio import GradoRepository
from .universidad_repositorio import UniversidadRepository
from .tipodocumento_repositorio import TipoDocumentoRepository